# config/packages/twig.yaml
twig:
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    # ...

 # config/packages/twig.yaml
#twig:
    # ...

    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/assets/images': images

