# config/packages/twig.yaml
twig:
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    # ...

 # config/packages/twig.yaml
twig:
    # ...

    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/assets/images': images

# config/packages/twig.yaml
twig:
    # ...

    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/assets/styles': styles